name: Dbus-rs-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus at-spi2-core
    - name: Check
      run: cargo check --verbose --all
    - name: Run tests
      run: |
        export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork`
        cargo test --all -- --nocapture --color always
        cd dbus-codegen && cargo test --all --no-default-features -- --nocapture --color always

  build-mingw:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          mingw-w64-x86_64-dbus
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-rust
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork`
        cd dbus && cargo test --lib -- --nocapture --color always
